neptune_key: ''
neptune_project: 'Serre-Lab/self-sup'
path_db: '../ssl_db'
model: 'MocoV2'
dataset: 'NTU_SSL'
# trainer
gpus: 1
batch_size: 32
max_epochs: 80
num_workers: 6
flush_logs_every_n_steps: 100
log_every_n_steps: 50
ckpt_period: 3
# model
gradient_clip_val: 5
optimizer: adam
emb_dim: 128
num_negatives: 65536 #16384 #65536
encoder_momentum: 0.999
softmax_temperature: 0.09 # 0.05
learning_rate: 0.001 # 0.0008
momentum: 0.9
weight_decay: 0.0001
use_mlp: True
output_feature: 'seqlast'
epochs: 150
lr_decay_rate: 0.1
# arch
bidirectional: False
input_dim: 150
input_embedding: null
hidden_dim: 512
cell: 'GRU'
num_layers: 1
# data
train_split: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_seqs.npy'
train_split_labels: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_labels.npy'
train_transforms: NTUMoco2TrainTransformsTS # null
val_split: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_seqs.npy'
val_split_labels: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_labels.npy'
val_transforms: NTUMoco2EvalTransformsTS # null
drop_last: True
shuffle: True