neptune_key: ''
neptune_project: 'Serre-Lab/self-sup'
path_db: '../ssl_db'
model: 'AutoEncPC'
dataset: 'UCLA_SSL'
# trainer
gpus: 1
batch_size: 64
max_epochs: 100
num_workers: 4
flush_logs_every_n_steps: 200
log_every_n_steps: 100
ckpt_period: 10
# model
optimizer: adam
learning_rate: 0.003
gradient_clip_val: 25
use_mlp: True
output_feature: 'seqlast'
decoder_input: 'seqlast'
#arch
bidirectional: True
input_dim: 60
input_embedding: null
hidden_dim: 512
cell: 'GRU'
num_layers: 1
# data
train_split: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/UCLAdata/UCLAtrain50.h5py'
train_transforms: null
val_split: '/cifs/data/tserre_lrs/projects/prj_ssl_ntu/UCLAdata/UCLAtest50.h5py'
val_transforms: null