neptune_key: ''
neptune_project: 'Serre-Lab/self-sup'
path_db: '../ssl_db'
model: 'MocoV2'
dataset: 'NTU_SSL'
# trainer
gpus: 1
batch_size: 64
max_epochs: 150
num_workers: 4
flush_logs_every_n_steps: 100
log_every_n_steps: 50
# model
emb_dim: 128
num_negatives: 65536
encoder_momentum: 0.999
softmax_temperature: 0.07
learning_rate: 0.03
momentum: 0.9
weight_decay: 0.0001
use_mlp: True
output_feature: 'last'
epochs: 150
lr_decay_rate: 0.1
#arch
bidirectional: True
input_dim: 150
input_embedding: null
hidden_dim: 512
cell: 'LSTM'
num_layers: 1
# data
# train_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/train_data.npy'
# train_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/train_label.pkl'
train_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_seqs.npy'
train_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_labels.pkl'
train_transforms: Moco2TrainTransforms # null
# val_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/val_data.npy'
# val_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/val_label.pkl'
val_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_seqs.npy'
val_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_labels.pkl'
val_transforms: Moco2EvalTransforms # null
ntu_type: 'ntu'
ntu_use_mmap: True