neptune_key: ''
neptune_project: 'Serre-Lab/self-sup'
path_db: '../ssl_db'
model: 'MocoBUTDcon'
dataset: 'NTU_SSL'
# trainer
gpus: 1
batch_size: 32
max_epochs: 80
num_workers: 4
flush_logs_every_n_steps: 50
log_every_n_steps: 50
ckpt_period: 3
# model
gradient_clip_val: 25
optimizer: adam
emb_dim: 128
num_negatives_BU: 16384 #4096
num_negatives_TD: 2048 #1024
encoder_momentum: 0.999
maximum_timesteps: 50
softmax_temperature: 0.1
learning_rate: 0.05 #0.03
momentum: 0.9
weight_decay: 0.0001
output_feature: 'seqlast'
epochs: 150
lr_decay_rate: 0.1
decoder_input: 'seqlast'
# weights
weight_bu: 1 # 1
weight_td: 1 # 1
weight_bu_sim: 1  # 25
weight_td_sim: 0 # 50
#arch
bidirectional: False
input_dim: 150
input_embedding: null
hidden_dim: 512
cell: 'GRU'
num_layers: 3
# data
train_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_seqs.npy'
train_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_train_labels.npy'
train_transforms: NTUMocoTDTrainTransformsTS # null
val_split: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_seqs.npy'
val_split_labels: '/media/data_cifs_lrs/projects/prj_ssl_ntu/NTU60/NTU60/xsub/NTU_val_labels.npy'
val_transforms: NTUMocoTDEvalTransformsTS # null
drop_last: True
shuffle: True
