path_db: '../ssl_db'
model: 'VAEPC'
dataset: 'UCLA_SSL'
# trainer
gpus: 1
batch_size: 32
max_epochs: 150
num_workers: 4
flush_logs_every_n_steps: 200
log_every_n_steps: 100
ckpt_period: 3
# model
optimizer: adam
learning_rate: 0.003
gradient_clip_val: 25 # 5
output_feature: 'seqlast'
#arch
bidirectional: False
input_dim: 60
input_embedding: null
hidden_dim: 512
#latent_dim: 512
cell: 'GRU'
num_layers: 1
beta: 0.02 # best 0.1
# data
train_split: '../UCLAdata/UCLAtrain50.h5py'
train_transforms: null
val_split: '../UCLAdata/UCLAtest50.h5py'
val_transforms: null
#drop_last: False
#shuffle: True