path_db: '../ssl_db'
model: 'TDCon'
dataset: 'UCLA_SSL'
# trainer
gpus: 1
batch_size: 32
max_epochs: 400
num_workers: 4
flush_logs_every_n_steps: 50
log_every_n_steps: 50
ckpt_period: 10
# model
gradient_clip_val: 25
optimizer: adam
# emb_dim: 128
num_negatives: 1024
encoder_momentum: 0.999
maximum_timesteps: 50
softmax_temperature: 0.1
learning_rate: 0.003 #0.03
momentum: 0.9
weight_decay: 0.0001
output_feature: 'seqlast'
epochs: 150
lr_decay_rate: 0.1
decoder_input: 'seqlast'
con_weight: 1
rec_weight: 25
#arch
bidirectional: False
input_dim: 60
input_embedding: null
hidden_dim: 512
cell: 'GRU'
num_layers: 1
# data
train_split: '../UCLAdata/UCLAtrain50.h5py'
train_transforms: UCLATDConTransformsTS
val_split: '../UCLAdata/UCLAtest50.h5py'
val_transforms: UCLATDConTransformsTS # null
