path_db: '../ssl_db'
model: 'MocoPlusAE'
dataset: 'UCLA_SSL'
# trainer
gpus: 1
batch_size: 32
max_epochs: 300
num_workers: 4
flush_logs_every_n_steps: 100
log_every_n_steps: 50
ckpt_period: 10
# model
# gradient_clip_val: 25
optimizer: adam
emb_dim: 128
num_negatives: 16384
encoder_momentum: 0.999
softmax_temperature: 0.06
learning_rate: 0.004
momentum: 0.9
weight_decay: 0.0001
use_mlp: True
output_feature: 'seqlast'
decoder_input: 'seqlast'
epochs: 300
lr_decay_rate: 0.1
td_loss_weight: 1
bu_loss_weight: 1
sim_loss_weight: 1 # 0 #
#arch
bidirectional: False
input_dim: 60
input_embedding: null
hidden_dim: 512
cell: 'GRU'
num_layers: 1
# data
train_split: '../UCLAdata/UCLAtrain50.h5py'
train_transforms: UCLAMocoTDTrainTransformsTS
val_split: '../UCLAdata/UCLAtest50.h5py'
val_transforms: UCLAMocoTDTrainTransformsTS # null